# Generated by Django 5.2.6 on 2025-12-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='номер заявки')),
                ('customer_name', models.CharField(max_length=100, verbose_name='имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='email клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='телефон клиента')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за день')),
                ('total_days', models.PositiveIntegerField(verbose_name='количество дней')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая стоимость')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма залога')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе аренды'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий клиента')),
                ('admin_notes', models.TextField(blank=True, verbose_name='заметки менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='catalog.tool', verbose_name='инструмент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка на аренду',
                'verbose_name_plural': 'заявки на аренду',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number'], name='rentals_ren_number_2d3c91_idx'), models.Index(fields=['status', '-created_at'], name='rentals_ren_status_dbd5a0_idx'), models.Index(fields=['user', '-created_at'], name='rentals_ren_user_id_e26481_idx')],
            },
        ),
    ]
