# Generated by Django 5.2.9 on 2026-03-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rental_id_photos/%Y/%m/', verbose_name='фото удостоверения личности'),
        ),
    ]
