# Generated by Django 5.2.12 on 2026-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='напоминание отправлено'),
        ),
    ]
