# Generated by Django 5.2.6 on 2025-12-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='изображение')),
                ('icon', models.CharField(blank=True, help_text='Например: icon-drill, icon-hammer', max_length=50, verbose_name='CSS-класс иконки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='краткое описание')),
                ('image', models.ImageField(upload_to='tools/', verbose_name='основное изображение')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='бренд')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='модель')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Технические характеристики в формате JSON', verbose_name='характеристики')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за день')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='залог')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное')], default='excellent', max_length=20, verbose_name='состояние')),
                ('availability', models.CharField(choices=[('available', 'Доступен'), ('rented', 'В аренде'), ('maintenance', 'На обслуживании'), ('unavailable', 'Недоступен')], default='available', max_length=20, verbose_name='доступность')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('quantity_available', models.PositiveIntegerField(default=1, verbose_name='доступное количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='рекомендуемый')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'инструмент',
                'verbose_name_plural': 'инструменты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tools/gallery/', verbose_name='изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.tool', verbose_name='инструмент')),
            ],
            options={
                'verbose_name': 'изображение инструмента',
                'verbose_name_plural': 'изображения инструментов',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['slug'], name='catalog_too_slug_a16db0_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'is_active'], name='catalog_too_categor_bfa3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['availability'], name='catalog_too_availab_b01ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_featured', '-created_at'], name='catalog_too_is_feat_9c4f8f_idx'),
        ),
    ]
